### ISSUE TITLE
Why not use imgui in vcpkg?

### ISSUE THREAD

**Issue by QiuYilin** [alvadeli/imgui-pcl#1]
There is imgui in vcpkg, why not use this version to simplify the compilation steps.

```
PS E:\src\vcpkg> .\vcpkg.exe search imgui
daxa[utils-imgui]                         The ImGUI Daxa utility
hello-imgui              1.4.2#1          Hello ImGui: unleash your creativity in app development and prototyping
hello-imgui[experimental-dx11-binding]    Use DirectX11 renderer backend (Windows only, experimental)
hello-imgui[experimental-dx12-binding]    Use DirectX12 renderer backend (Windows only, experimental)
hello-imgui[experimental-vulkan-binding]  Use Vulkan renderer backend (Windows/Linux/macOS, experimental)
hello-imgui[freetype-lunasvg]             Improve font rendering and use colored fonts with freetype and lunasvg
hello-imgui[glfw-binding]                 Use GLFW platform backend (default)
hello-imgui[metal-binding]                Use Metal renderer backend (macOS/iOS only)
hello-imgui[opengl3-binding]              Use OpenGL3/ES2 renderer backend (default)
hello-imgui[sdl2-binding]                 Use SDL2 platform backend
imgui                    1.90.7           Bloat-free Immediate Mode Graphical User interface for C++ with minimal de...
```

**Comment by alvadeli** [comment]
@QiuYilin I think including imgui with vcpkg is the simpler approach. But I like having quick access to the examples and source files of the imgui examples. They helped me a lot to understand and implement GUI features with imgui.  
My workflow was often to use the examples window and look how the things I needed/found interesting were implemented with the .cpp files. 
Like how this Youtuber presented it:   [BEST WAY to make Desktop Applications in C++](https://www.youtube.com/watch?v=vWXrFetSH8w&t=267s)
I don't know if this is possible with vcpkg. Maybe I missed something, or how do you use the examples if you want to look something up in the .cpp files.

**Comment by QiuYilin** [comment]
>But I like having quick access to the examples and source files of the imgui examples. They helped me a lot to understand and implement GUI features with imgui.My workflow was often to use the examples window and look how the things I needed/found interesting were implemented with the .cpp files.

This is indeed the more recommended approach by imgui：https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L19

>I don't know if this is possible with vcpkg. Maybe I missed something, or how do you use the examples if you want to look something up in the .cpp files.

Emmm, in the past, I would download another imgui or read the manual https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html. Now I think if I use the vcpkg version I may need to additionally copy and paste imgui_demo.cpp. I think this question is not important, I just remind you in case you don't know that vcpkg has an imgui version. This video is very helpful to me, thank you.
